# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Culture Amp’s Living Style Guide
email: kevin@cultureamp.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cultureamp.github.io/cultureamp-style-guide" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:title

# Build settings
destination: dist
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - index.js
  - index.scss
  - webpack.config.js
  - src
  - assets/manifest.json
collections:
  visuals:
    output: true
    page: visuals.md
  atoms:
    output: true
    page: atoms.md
  molecules:
    output: true
    page: molecules.md
  organisms:
    output: true
    page: organisms.md
  templates:
    output: true
    page: templates.md
  sample-pages:
    output: true
    page: pages.md
defaults:
  -
    scope:
      path: ""
    values:
      layout: collection
  -
    scope:
      path: ""
      type: visuals
    values:
      layout: component
  -
    scope:
      path: ""
      type: atoms
    values:
      layout: component
  -
    scope:
      path: ""
      type: molecules
    values:
      layout: component
  -
    scope:
      path: ""
      type: organisms
    values:
      layout: component
  -
    scope:
      path: ""
      type: templates
    values:
      layout: component
  -
    scope:
      path: ""
      type: sample-pages
    values:
      layout: component
